# Generated by Django 2.1.5 on 2019-01-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='例如：用户删除权限不能做菜单，但是点击这个选项，会使得用户列表这个菜单处于被激活状态', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='rbac.Permission', verbose_name='关联权限'),
        ),
    ]
